export const layoutTypes = {
  /* LAYOUT */
  CHANGE_LAYOUT: 'CHECK_CHANGE_LAYOUTLOGIN',
  CHANGE_LAYOUT_WIDTH: 'CHANGE_LAYOUT_WIDTH',
  CHANGE_SIDEBAR_THEME: 'CHANGE_SIDEBAR_THEME',
  CHANGE_SIDEBAR_TYPE: 'CHANGE_SIDEBAR_TYPE',

  // topbar
  CHANGE_TOPBAR_THEME: 'CHANGE_TOPBAR_THEME',

  /* RIGHT SIDEBAR  */
  TOGGLE_RIGHT_SIDEBAR: 'TOGGLE_RIGHT_SIDEBAR',
  SHOW_RIGHT_SIDEBAR: 'SHOW_RIGHT_SIDEBAR',
  HIDE_RIGHT_SIDEBAR: 'HIDE_RIGHT_SIDEBAR',

  // Preloader
  HIDE_RIGHT_SIDEBAR: 'HIDE_RIGHT_SIDEBAR',

  // Confirm
  CONFIRM_MODEL_ON: 'CONFIRM_MODEL_ON',
  CONFIRM_MODEL_OFF: 'CONFIRM_MODEL_OFF',
}
