export const employeeTypes = {
  //Fetch Employee
  GET_EMPLOYEES_REQUEST: 'GET_EMPLOYEES_REQUEST',
  GET_EMPLOYEES_SUCCESS: 'GET_EMPLOYEES_SUCCESS',
  GET_EMPLOYEES_ERROR: 'GET_EMPLOYEES_ERROR',

  //ADD Employee
  ADD_EMPLOYEES_REQUEST: 'ADD_EMPLOYEES_REQUEST',
  ADD_EMPLOYEES_SUCCESS: 'ADD_EMPLOYEES_SUCCESS',
  ADD_EMPLOYEES_ERROR: 'ADD_EMPLOYEES_ERROR',

  //Edit Employee
  EDIT_EMPLOYEES_REQUEST: 'EDIT_EMPLOYEES_REQUEST',
  EDIT_EMPLOYEES_SUCCESS: 'EDIT_EMPLOYEES_SUCCESS',
  EDIT_EMPLOYEES_ERROR: 'EDIT_EMPLOYEES_ERROR',

  //Fetch Route Name
  GET_ROUTENAME_REQUEST: 'GET_ROUTENAME_REQUEST',
  GET_ROUTENAME_SUCCESS: 'GET_ROUTENAME_SUCCESS',
  GET_ROUTENAME_ERROR: 'GET_ROUTENAME_ERROR',
}
