export const assignmentTypes = {
  //Fetch Vendor
  GET_ASSIGNMENTS_REQUEST: 'GET_ASSIGNMENTS_REQUEST',
  GET_ASSIGNMENTS_SUCCESS: 'GET_ASSIGNMENTS_SUCCESS',
  GET_ASSIGNMENTS_ERROR: 'GET_ASSIGNMENTS_ERROR',

  //ADD Vendor
  ADD_ASSIGNMENTS_REQUEST: 'ADD_ASSIGNMENTS_REQUEST',
  ADD_ASSIGNMENTS_SUCCESS: 'ADD_ASSIGNMENTS_SUCCESS',
  ADD_ASSIGNMENTS_ERROR: 'ADD_ASSIGNMENTS_ERROR',

  //Edit Vendor
  EDIT_ASSIGNMENTS_REQUEST: 'EDIT_ASSIGNMENTS_REQUEST',
  EDIT_ASSIGNMENTS_SUCCESS: 'EDIT_ASSIGNMENTS_SUCCESS',
  EDIT_ASSIGNMENTS_ERROR: 'EDIT_ASSIGNMENTS_ERROR',

  //Fetch Route Name
  GET_ROUTENAME_REQUEST: 'GET_ROUTENAME_REQUEST',
  GET_ROUTENAME_SUCCESS: 'GET_ROUTENAME_SUCCESS',
  GET_ROUTENAME_ERROR: 'GET_ROUTENAME_ERROR',

  //Delete Vendor
  // DELETE_ASSIGNMENTS_REQUEST: "DELETE_ASSIGNMENTS_REQUEST",
  // DELETE_ASSIGNMENTS_SUCCESS: "DELETE_ASSIGNMENTS_SUCCESS",
  // DELETE_ASSIGNMENTS_ERROR: "DELETE_ASSIGNMENTS_ERROR",

  // DELETE_MULTIPLE_ASSIGNMENTS_REQUEST: "DELETE_MULTIPLE_ASSIGNMENTS_REQUEST",
  // DELETE_MULTIPLE_ASSIGNMENTS_SUCCESS: "DELETE_MULTIPLE_ASSIGNMENTS_SUCCESS",
  // DELETE_MULTIPLE_ASSIGNMENTS_ERROR: "DELETE_MULTIPLE_ASSIGNMENTS_ERROR",

  //Image Vendor
  // IMAGE_ASSIGNMENTS_REQUEST: "DELETE_ASSIGNMENTS_REQUEST",
  // IMAGE_ASSIGNMENTS_SUCCESS: "DELETE_ASSIGNMENTS_SUCCESS",
  // IMAGE_ASSIGNMENTS_ERROR: "DELETE_ASSIGNMENTS_ERROR",

  //Fetch Exel Sheet Name
  // POST_EXELSHEET_REQUEST: "POST_EXELSHEET_REQUEST",
  // POST_EXELSHEET_SUCCESS: "POST_EXELSHEET_SUCCESS",
  // POST_EXELSHEET_ERROR: "POST_EXELSHEET_ERROR",
}
