export const assetTypes = {
  //Fetch Assets
  GET_ASSETS_REQUEST: 'GET_ASSETS_REQUEST',
  GET_ASSETS_SUCCESS: 'GET_ASSETS_SUCCESS',
  GET_ASSETS_ERROR: 'GET_ASSETS_ERROR',

  //Fetch AssetTypes
  GET_ASSETTYPE_REQUEST: 'GET_ASSETTYPE_REQUEST',
  GET_ASSETTYPE_SUCCESS: 'GET_ASSETTYPE_SUCCESS',
  GET_ASSETTYPE_ERROR: 'GET_ASSETTYPE_ERROR',

  //ADD Assets
  ADD_ASSETS_REQUEST: 'ADD_ASSETS_REQUEST',
  ADD_ASSETS_SUCCESS: 'ADD_ASSETS_SUCCESS',
  ADD_ASSETS_ERROR: 'ADD_ASSETS_ERROR',

  //Edit Assets
  EDIT_ASSETS_REQUEST: 'EDIT_ASSETS_REQUEST',
  EDIT_ASSETS_SUCCESS: 'EDIT_ASSETS_SUCCESS',
  EDIT_ASSETS_ERROR: 'EDIT_ASSETS_ERROR',

  // //Fetch Route Name
  // GET_ROUTENAME_REQUEST: 'GET_ROUTENAME_REQUEST',
  // GET_ROUTENAME_SUCCESS: 'GET_ROUTENAME_SUCCESS',
  // GET_ROUTENAME_ERROR: 'GET_ROUTENAME_ERROR',

  //Delete Assets
  // DELETE_ASSETS_REQUEST: "DELETE_ASSETS_REQUEST",
  // DELETE_ASSETS_SUCCESS: "DELETE_ASSETS_SUCCESS",
  // DELETE_ASSETS_ERROR: "DELETE_ASSETS_ERROR",

  // DELETE_MULTIPLE_ASSETS_REQUEST: "DELETE_MULTIPLE_ASSETS_REQUEST",
  // DELETE_MULTIPLE_ASSETS_SUCCESS: "DELETE_MULTIPLE_ASSETS_SUCCESS",
  // DELETE_MULTIPLE_ASSETS_ERROR: "DELETE_MULTIPLE_ASSETS_ERROR",

  //Image Vendor
  // IMAGE_ASSETS_REQUEST: "DELETE_ASSETS_REQUEST",
  // IMAGE_ASSETS_SUCCESS: "DELETE_ASSETS_SUCCESS",
  // IMAGE_ASSETS_ERROR: "DELETE_ASSETS_ERROR",

  //Fetch Exel Sheet Name
  // POST_EXELSHEET_REQUEST: "POST_EXELSHEET_REQUEST",
  // POST_EXELSHEET_SUCCESS: "POST_EXELSHEET_SUCCESS",
  // POST_EXELSHEET_ERROR: "POST_EXELSHEET_ERROR",
}
